### ISSUE TITLE
How would we center the tags?

### ISSUE THREAD

**Issue by sehunchoi** [xhacker/TagListView#10]
I would like to center all the tags so we don't have all the spaces in the right of our view.
Like Flipboard for example:
![img_1109](https://cloud.githubusercontent.com/assets/11592061/9066956/5a4106e4-3a8f-11e5-9fcf-07c35a05020b.PNG)

How would we get this to work??

**Comment by pizthewiz** [comment]
In some ways ways the container `TagListView` is quite like a stack view with additional proxying/factory stuff for the specialized tag child views. If this project were to only target iOS 9, it wouldn't be difficult to re-craft `TagListView` as a `UIStackView` subclass and gain a fair amount of layout functionality, but we'd either need to create our own, or pull in an external dependency like [OAStackView](https://github.com/oarrabi/OAStackView) to support earlier releases.

**Comment by xhacker** [comment]
Currently we can’t center the tags. If you’d like to contribute, take a look at https://github.com/xhacker/TagListView/blob/master/TagListView/TagListView.swift#L125-L154. I could also help when I get some time. :)

@pizthewiz: Yeah `UIStackView` would be really handy.

**Comment by pizthewiz** [comment]
Just noting that something like [TZStackView](https://github.com/tomvanzummeren/TZStackView) might be a better fit than [OAStackView](https://github.com/oarrabi/OAStackView) since it is API complete / compatible with `UIStackView`, so if/when iOS 9 became the minimum, it could just be replaced with `UIStackView` without much fuss.

**Comment by bassebaba** [comment]
I would like to be able to have the tags start from bottom-right, is this also impossible at the moment?

**Comment by xhacker** [comment]
@bassebaba: Sorry, not possible at this moment.

**Comment by xhacker** [comment]
This has been implemented in the latest version (0.4).
