### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by maxykato** [xhacker/TagListView#18]
Got some errors on Xcode 7.0
Any plan to make it compatible with Swift 2.0?

**Comment by maxykato** [comment]
I just found that there is a brach for Swift 2.0.
The issue was resolved by having the below line in my podfile.
pod 'TagListView', :git => 'https://github.com/xhacker/TagListView', :branch => 'swift-2.0'

**Comment by xhacker** [comment]
Thanks for reminding me though. `swift-2.0` branch should be default now.
