### ISSUE TITLE
Deleting tags

### ISSUE THREAD

**Issue by jyounus** [xhacker/TagListView#2]
Hey,

I haven't downloaded or played with the code yet, but this is something I'm thinking of using very soon in my app. I was just wondering if maybe there's a way to have something like an "X" to delete and its own dedicated touch event for it? 

So in other words, I'd like the user to be easily remove tags manually by pressing the "X" icon, without having to go into an "edit" mode. I was thinking of having a the "X" to the left and then to the right the normal text.

**Comment by xhacker** [comment]
Good request. I will implement it when I get some time. BTW pull requests are welcome. :)

**Comment by XBeg9** [comment]
What do you think if we add ability for left and right view? So you can add any icon, button there and make own behaviour.

**Comment by xhacker** [comment]
@XBeg9: Actually with your recent patch, TagView is now exposed. Users are now able to do whatever they want to the TagView. I really don’t want to make TagListView too complicated. Thoughts?

cc @jyounus

**Comment by XBeg9** [comment]
@xhacker imagine if someone asks drag&drop :) then it's too complicated. I think add left / right is fine, for example just to add icon.

**Comment by xhacker** [comment]
@XBeg9: Agreed. Feel free to contribute if you like. :)

**Comment by xhacker** [comment]
Done by @entotsu and @Benuuu :)
