### ISSUE TITLE
Add tagview from another taglistview

### ISSUE THREAD

**Issue by jdgong** [xhacker/TagListView#21]
Hi

Is it possible to add/copy tagview from a taglistview to another taglistview now? I tried, but it just freeze and seems to be in a infinite loop eating up all memory. TagView is not conformed to nscopy so it seems I have to recreate the same tagview using all the attributes again. Any thing I missed?

**Comment by xhacker** [comment]
You are right, currently you can't copy a tag view. Instead, you can just create new tag views using the same content.
