### ISSUE TITLE
Get specific tag ?

### ISSUE THREAD

**Issue by pc660** [xhacker/TagListView#28]
Hi, I really like your tagList but I have some customized requests.
I would like to add a feature that allow me to do a customized filter, like the filter selectedTags()
I think maybe you can add a public function that pass a block and then user can specify their own customized filter. e.g, I wanna pick the tag with certain titles, etc.

I can add a pull request if you want, but I am not sure whether this feature is sth you also want to do.

**Comment by xhacker** [comment]
If I understand correctly, you want to get a `[TagView]` in which all tags satisfy some properties? If that’s the case, I’d say you can just use the Swift filter like I did in `selectedTags`:
```swift
tagViews.filter() { $0.selected == true }
```

**Comment by pc660** [comment]
Yeah, exactly. But, tagViews is a private attribute and cannot be accessed from outside. Maybe I am wrong?

**Comment by xhacker** [comment]
Good point. I just made a commit, now it’s public. Let me know if it works. :)

**Comment by pc660** [comment]
Sure. really helps.:)
