### ISSUE TITLE
Array of tags

### ISSUE THREAD

**Issue by lmick002** [xhacker/TagListView#29]
Ability to add an Array of Strings ex. biggerTagListView.addTags("Inboard","Onboard","Outboard")

**Comment by xhacker** [comment]
I don’t think it’s necessary to add this API. You could just use a for loop:
```swift
for tag in ["Inboard", "Onboard", "Outboard"] {
    biggerTagListView.addTag(tag)
}
```
or even `map`:
```swift
["Inboard", "Onboard", "Outboard"].map({ biggerTagListView.addTag($0) })
```
