### ISSUE TITLE
IBDesignable doesn’t work with Carthage

### ISSUE THREAD

**Issue by entotsu** [xhacker/TagListView#30]
Could you use @IBDesignable in storyboard when you install this via Carthage? :cold_sweat: 

related issue:  [Carthage/issues/335](https://github.com/Carthage/Carthage/issues/335)

**Comment by xhacker** [comment]
Thanks for reporting. However, I don’t see anything we can do on our side.

**Comment by entotsu** [comment]
:+1:

**Comment by xhacker** [comment]
Closing because this is Apple issue.
