### ISSUE TITLE
 IB Designables: Failed to render instance of TagListView

### ISSUE THREAD

**Issue by senseluo** [xhacker/TagListView#36]
Just upgrade to version 0.5 but some errors as below generate by Xcode.

`Main.storyboard: error: IB Designables: Failed to render instance of TagListView: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.`

Not sure if it was introduced by new version.

Thanks!

**Comment by xhacker** [comment]
Which version of Xcode are you using?

**Comment by senseluo** [comment]
Version 7.2.1 (7C1002)

**Comment by xhacker** [comment]
I think this is an Xcode issue. If it compiles, you can just ignore it.
