### ISSUE TITLE
Tags of different colors in one block

### ISSUE THREAD

**Issue by Russakill** [xhacker/TagListView#4]
Hey, 

It would be cool to choose the color for each tag individually, rather than the entire set completely. What do you think about this?

Thank you.

**Comment by xhacker** [comment]
Good idea. I will implement it when I get some time. BTW pull requests are welcome. :)

**Comment by thierryskoda** [comment]
+1

**Comment by xhacker** [comment]
Fixed in 0.2. Thanks @XBeg9!
