### ISSUE TITLE
NSAttributedString support for tag label text coloring

### ISSUE THREAD

**Issue by JacobSyndeo** [xhacker/TagListView#41]
Is it possible to have different colors of text within the tags? For example, have one part of the tag's text be green, while another section is black? I'm thinking an NSAttributedString would fit here.
I'm trying to replicate the tags shown in this webpage:
![img_1395](https://cloud.githubusercontent.com/assets/1004637/14577878/7ecc2d0e-0348-11e6-84d4-21ae7c6aa680.PNG)

**Comment by xhacker** [comment]
Since `TagView` is a subclass to UIButton, you can always use `setAttributedTitle:forState:` to change the attributed title. Let me know if it works.

**Comment by abdulla-allaith** [comment]
Please comment on PR #250, it contains support for Attributed String.
For now, you can use [abdulla-allaith/TagListView](https://github.com/abdulla-allaith/TagListView), which has the PR merged.
