### ISSUE TITLE
Incorrect sizing in UITableViewCell depending on frame in storyboard (project attached)

### ISSUE THREAD

**Issue by UberJason** [xhacker/TagListView#43]
Hi there,

I've noticed that the TagListView, when configured in a UITableViewCell in a storyboard, may incorrectly render with the bottom cut off depending on the size of the view controller in the storyboard. I've created a quick project to demonstrate the problem: https://github.com/UberJason/TagListViewStoryboardBug

I tried to look through the code of TagListView quickly, but nothing jumped out at me to explain the problem. Hope you might have a better idea than I do!

**Comment by UberJason** [comment]
I also noticed that when a TagListView is embedded in a UITableViewCell in a table using self-sizing cells, and then you start adding tags to the view and call reloadData() after each one, the cell doesn't grow when a new line is needed - the tag just gets cut off. 

I checked, and the calculation of intrinsicContentSize() is called a few times, and the first time it's returning the old height, but the second time it's returning the new and correct height - I'm not sure if this might be the problem? Maybe the table view only asks for the intrinsicContentSize the first time, when returning the wrong size. Sadly I'm no auto-layout wizard so I'm not sure what's happening here, but if you could take a look, it'd be appreciated!

**Comment by xhacker** [comment]
Auto layout with automatic cell height is always tricky. I looked into your repo and didn’t figure out a solution.

I actually have a repo that uses TagListView and auto cell height. You might want to take a look: https://github.com/xhacker/Stargazer-iOS

Switch to the Stars tab, drill into All, and choose a repo. Then you can add a lot of tags to it.
<img src="https://cloud.githubusercontent.com/assets/1051813/14940634/2de0c2aa-0f33-11e6-861d-fbdb13400002.png" width="320">

**Comment by UberJason** [comment]
Thanks for taking a look; hope you figure it out eventually. :) For now, I've got TagListView working with self-sizing cells myself, just by making the storyboard smaller to start (as I showed works in that project).

**Comment by raphaklr** [comment]
@UberJason Could you tell me, what your error was? I'm facing the exact same problem.

**Comment by UberJason** [comment]
@raphaklr In my crossed-out comment? I forgot to add tableView.rowHeight = UIAutomaticDimension. That actually seems to make all the difference.

**Comment by raphaklr** [comment]
@UberJason In my case, the tags still get cut off, even though I set `tableView.rowHeight = UIAutomaticDimension` 😔 Thank you anyway!

**Comment by aleene** [comment]
The problem seems to be when the actual height is calculated. Try to reload at a later phase in the controller lifecycle, for instance in viewDidAppear.
See also: http://useyourloaf.com/blog/self-sizing-table-view-cells/

**Comment by UberJason** [comment]
@aleene: Yes, that works, but it introduces a "flicker" where the tag list view is initially cut-off, and then jarringly "jumps" into the correct size. That shouldn't be necessary.

**Comment by aleene** [comment]
True, use tableView.reloadRowsAtIndexPaths to avoid the flicker

**Comment by UberJason** [comment]
Thanks for the suggestion, but that only makes the flicker "look nicer". The point really is that the initial view shows the row cut off, and that should not be necessary - it's a hack, not a solution.

**Comment by aleene** [comment]
Agree, but is something Apple should solve. Maybe you can fiddle with the estimated height (make it larger), I did not experiment enough with it (yet).

**Comment by UberJason** [comment]
Ah I misunderstood. Thanks for trying to help! As I mentioned earlier in the thread, I've got TagListView working with self-sizing cells just by making the storyboard smaller to start.

**Comment by zuo305** [comment]
resolved.
use UIScreen.mainScreen().bounds.size.width replace frame.width in TagListView.swift

**Comment by UberJason** [comment]
Does that handle the case where the TagListView does not take up the entire width of the screen?

**Comment by zuo305** [comment]
for example:

if currentRowTagCount == 0 || currentRowWidth + tagView.frame.width > UIScreen.mainScreen().bounds.size.width{

**Comment by raphaklr** [comment]
@zuo305 Imagine your app runs on an iPad in slideover mode. Then `UIScreen.mainScreen().bounds.size.width` would be the width of the entire iPad display. I'm pretty sure this would break the layout.

**Comment by zuo305** [comment]
ok, the resolve way is : change the "frame.width" to the expected width. Today i will upload a new pic for different width of taglistview.

**Comment by zuo305** [comment]
@UberJason I download your project and change the code ,and now it worked. how can I send you the new project? 
<img width="1209" alt="screen shot 2016-05-06 at 9 51 29 am" src="https://cloud.githubusercontent.com/assets/4032158/15060649/26c36388-1370-11e6-8caa-e34b8b99c346.png">

**Comment by UberJason** [comment]
@zuo305 Thanks for your assistance; I actually already have a workaround, as I had mentioned previously. Hopefully at some point in the future this bug will be resolved in a way that doesn't require workarounds like setting a width in advance.

**Comment by xhacker** [comment]
Thank you guys! Closing since there’s a workaround.
