### ISSUE TITLE
Set Module of TagListView

### ISSUE THREAD

**Issue by blwinters** [xhacker/TagListView#45]
This isn't necessarily an issue, but you may want to mention in the installation instructions that if they use Cocoapods, they need to set the Module of the UIView/TagListView in the storyboard to TagListView. I never had to do this before and the sample project didn't need it, so it took me a while to realize why I was getting the error: "Unknown class TagListView in Interface Builder file".

**Comment by xhacker** [comment]
Thanks Ben! Mentioned that in readme.
