### ISSUE TITLE
Programmatically select tag

### ISSUE THREAD

**Issue by gkye** [xhacker/TagListView#48]
Is it possible to programmatically select a tag? I wish to select a tag when its added if its not already contained in my array of tags. Currently the method below works when the tag is not within the array but I'm not too sure how to go about it when the tag is contained in the array. I could remove the tag, add it and use the same method below but that seems quite tedious. I was wondering if there was a better solution? 

**Add new tag and select** 
```swift
  let tagView = self.tagListView.addTag(text)
  self.tagPressed(text, tagView: tagView, sender: self.tagListView)
```
**Programmatically select tag**
```swift
  tagListView.removeTag(text)
  let tagView = self.tagListView.addTag(text)
  self.tagPressed(text, tagView: tagView, sender: self.tagListView)
```

**Comment by xhacker** [comment]
It’s actually quite simple:

```swift
let tagView = tagListView.addTag("This tag will be selected")
tagView.selected = true
```
