### ISSUE TITLE
Tags Pinyin input method problem－－标签拼音输入法问题

### ISSUE THREAD

**Issue by zhanglizhong1002** [xhacker/TagListView#56]
The label when using Pinyin input method, found that most can only play three words, and more than three will automatically enter, seek to resolve under author

Thank you hope to get the author's reply

标签使用拼音输入法时，发现最多只能打三个字， 而且超过三个会自动enter，求作者解决下

**Comment by xhacker** [comment]
不太明白，可以截图或者截一段视频么？
