### ISSUE TITLE
"Cannot call value of non-function type" when trying to catch tap event

### ISSUE THREAD

**Issue by devloe** [xhacker/TagListView#58]
![captura de pantalla 2016-07-03 a las 2 25 15 1](https://cloud.githubusercontent.com/assets/122845/16543105/aa7011cc-40c5-11e6-9ed8-84cbd2bcfe95.png)

Any thoughts?

**Comment by xhacker** [comment]
Can you paste your code? It’s hard to copy from screenshot.

**Comment by devloe** [comment]
My mistake.

It should be tagView.onTap = {, not tagView.onTap{

**Comment by devloe** [comment]
Still cant get the tag to trigger click. I will post my code to see if you can help me out.
