### ISSUE TITLE
Change tag background color by user actions

### ISSUE THREAD

**Issue by maxykato** [xhacker/TagListView#6]
I want to set default tag bg color as gray and change it to some other color if user taps on tags. Is it possible? 

I took a look at the readme and sample codes, and I understood how to change bg color for all tags, but could not find how to change color for each tag. 

Could you give me advice?

BTW, This is such a great library. I really appreciate it.

**Comment by XBeg9** [comment]
+1

**Comment by maxykato** [comment]
Wow, thanks so much @XBeg9. I am looking forward to your commit to be merged and published.

**Comment by xhacker** [comment]
Fixed in 0.2. Thanks @XBeg9!
