### ISSUE TITLE
TagListView 1.0.1 Swift 3 error

### ISSUE THREAD

**Issue by DesmondPang** [xhacker/TagListView#73]
The version 1.0.1 is not the updated swift 3 but the master branch is the updated.  I use `pod 'TagListView', '~> 1.0'` but Xcode shows errors.  Did you make the wrong tag to the older version?

Even the latest source code file is not the Xcode 8 swift 3 syntax 
https://github.com/xhacker/TagListView/archive/1.0.1.zip

Thanks

**Comment by xhacker** [comment]
Yeah that’s intentional. `1.0.1` is for Swift 2. You could use `master` branch If you wanted to use Swift 3.
