### ISSUE TITLE
Any ETA of Swift 3 cocoapods version?

### ISSUE THREAD

**Issue by ghernagon** [xhacker/TagListView#76]
Need cococapod for swift 3, in previous comments the author said 1 or 2 days for swift 3 version, but was like 10 days ago, any news about it?

Thx

**Comment by JonathanRitcheyUS** [comment]
Would love to see support for Swift 3 too.

**Comment by RolandasRazma** [comment]
works for me targeting master

pod "TagListView", :git  => "git@github.com:xhacker/TagListView.git", :branch => "master"

**Comment by xhacker** [comment]
As @RolandasRazma said, you can use the `master` branch for Swift 3. I will need to fully test the library before making a new release.

**Comment by gsujathap** [comment]
![screen shot 2016-11-03 at 4 17 27 pm](https://cloud.githubusercontent.com/assets/16931145/19963147/1ea975f2-a1e1-11e6-963a-2c757cafb5e4.png)

@RolandasRazma I have done as u said But, I have got this error

**Comment by RolandasRazma** [comment]
@gsujathap try https one 

`pod "TagListView",  :git  => "https://github.com/xhacker/TagListView.git", :branch => "master"`

**Comment by RolandasRazma** [comment]
oh, it was moved. new URL is https://github.com/ElaWorkshop/TagListView.git

**Comment by gsujathap** [comment]
@RolandasRazma 
tagListView.addTag("some") ----> returns an error like EXC_Bad_Access. How to resolve this one. please help me out.

**Comment by gsujathap** [comment]
@RolandasRazma  thanks for your immediate response for that git clone
